output "resource_group_name" {
  description = "Name of the resource group"
  value       = azurerm_resource_group.main.name
}

output "service_bus_connection_string" {
  description = "Service Bus connection string"
  value       = module.service_bus.connection_string
  sensitive   = true
}

output "storage_connection_string" {
  description = "Storage account connection string"
  value       = module.storage.primary_connection_string
  sensitive   = true
}

output "container_registry_login_server" {
  description = "Container Registry login server"
  value       = module.container_registry.login_server
}

output "container_registry_admin_username" {
  description = "Container Registry admin username"
  value       = module.container_registry.admin_username
  sensitive   = true
}

output "container_registry_admin_password" {
  description = "Container Registry admin password"
  value       = module.container_registry.admin_password
  sensitive   = true
}

output "api_url" {
  description = "URL of the API (if Container Apps enabled)"
  value       = module.container_apps[0].api_url
}

output "storefront_url" {
  description = "URL of the storefront app"
  value       = module.container_apps[0].storefront_url
}

output "dashboard_url" {
  description = "URL of the dashboard app"
  value       = module.container_apps[0].dashboard_url
}

# Output for .env file generation
output "env_file_content" {
  description = "Content for .env file (excluding external secrets)"
  value       = <<-EOT
    # Azure Services (auto-generated by Terraform)
    AZURE_STORAGE_CONNECTION_STRING=${module.storage.primary_connection_string}
    AZURE_SERVICE_BUS_CONNECTION_STRING=${module.service_bus.connection_string}

    # Container Registry
    ACR_LOGIN_SERVER=${module.container_registry.login_server}
    ACR_USERNAME=${module.container_registry.admin_username}
    # ACR_PASSWORD - run: terraform output -raw container_registry_admin_password
  EOT
  sensitive   = true
}
