#!/bin/bash
set -e

# Generate .env file from Terraform outputs
# Usage: ./generate-env.sh <environment>

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$INFRA_DIR/terraform"
PROJECT_DIR="$(dirname "$INFRA_DIR")"

ENVIRONMENT="${1:-staging}"

if [[ ! "$ENVIRONMENT" =~ ^(staging|prod)$ ]]; then
    echo "Error: Environment must be 'staging' or 'prod'"
    echo "Usage: $0 <environment>"
    exit 1
fi

ENV_DIR="$TERRAFORM_DIR/environments/$ENVIRONMENT"
OUTPUT_FILE="$PROJECT_DIR/.env.$ENVIRONMENT"

echo "=== Generate .env file ==="
echo "Environment: $ENVIRONMENT"
echo "Output: $OUTPUT_FILE"
echo ""

cd "$ENV_DIR"

# Check if Terraform state exists
if ! terraform state list &> /dev/null; then
    echo "Error: Terraform state not found. Run 'deploy.sh $ENVIRONMENT apply' first."
    exit 1
fi

# Get outputs
STORAGE_CONN=$(terraform output -raw storage_connection_string 2>/dev/null || echo "")
SERVICEBUS_CONN=$(terraform output -raw service_bus_connection_string 2>/dev/null || echo "")
ACR_SERVER=$(terraform output -raw container_registry_login_server 2>/dev/null || echo "")
ACR_USERNAME=$(terraform output -raw container_registry_admin_username 2>/dev/null || echo "")
ACR_PASSWORD=$(terraform output -raw container_registry_admin_password 2>/dev/null || echo "")

# Generate .env file
cat > "$OUTPUT_FILE" << EOF
# Diamond Opus - $ENVIRONMENT Environment
# Auto-generated by generate-env.sh
# DO NOT COMMIT THIS FILE

# Database (Supabase - fill in manually)
DATABASE_URL=postgresql://user:pass@db.supabase.co:5432/postgres

# Nivoda API (fill in manually)
NIVODA_ENDPOINT=$([ "$ENVIRONMENT" == "prod" ] && echo "https://integrations.nivoda.net/api/diamonds" || echo "https://intg-customer-staging.nivodaapi.net/api/diamonds")
NIVODA_USERNAME=
NIVODA_PASSWORD=

# Azure Services (from Terraform)
AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONN
AZURE_SERVICE_BUS_CONNECTION_STRING=$SERVICEBUS_CONN

# Container Registry (from Terraform)
ACR_LOGIN_SERVER=$ACR_SERVER
ACR_USERNAME=$ACR_USERNAME
ACR_PASSWORD=$ACR_PASSWORD

# API Configuration
PORT=3000
# Alerts (fill in manually)
RESEND_API_KEY=
ALERT_EMAIL_TO=
ALERT_EMAIL_FROM=

# Pricing
PRICING_MODE=CONSOLIDATION
EOF

echo "Generated $OUTPUT_FILE"
echo ""
echo "Next steps:"
echo "1. Fill in the placeholder values (DATABASE_URL, NIVODA_*, RESEND_*, etc.)"
echo "2. Copy to .env for local development: cp $OUTPUT_FILE $PROJECT_DIR/.env"
